let g:floaterm_keymap_new = '<Leader>ft'
let g:floaterm_keymap_prev   = '<F8>'
let g:floaterm_keymap_next   = '<F9>'
let g:floaterm_keymap_kill = '<Leader>fk'
let g:floaterm_keymap_toggle = '<Leader>ftt'
